### PR TITLE
BUG make sure to compute the correlation coeff properly

### PR DESCRIPTION
**Pull request by beckermr**

### CODE REVIEW

**Comment by RickardSjogren** [comment]
Can you elaborate why you consider this a bug? I don't use this method myself. But according to the docstring the aim is to minimize the correlation between observations, which is what is currently calculated.

**Comment by beckermr** [comment]
The correlation coefficient is not computed correctly. Here is an example

```python
>>> import pyDOE
>>> lh = pyDOE.lhs(2, 100)
>>> lh.shape
(100, 2)
>>> np.corrcoef(lh).shape
(100, 100)
>>> np.corrcoef(lh.T).shape
(2, 2)
```

So without the transpose I added, the correlation matrix is for the wrong dimension.

**Comment by beckermr** [comment]
In other words, the code is not properly computing the correlation matrix of the observations.

**Comment by tmcclintock** [comment]
@beckermr 's observation is correct. We can see that by modifying `_lhscorrelat` in the default implementation to just print `mincorr`:
```
## in the file doe_lhs.py
def _lhscorrelate(n, samples, iterations, randomstate):
    mincorr = np.inf
    
    # Minimize the components correlation coefficients
    for i in range(iterations):
        # Generate a random LHS
        Hcandidate = _lhsclassic(n, samples, randomstate)
        R = np.corrcoef(Hcandidate)
        print mincorr
        if np.max(np.abs(R[R!=1]))<mincorr:
            mincorr = np.max(np.abs(R-np.eye(R.shape[0])))
            H = Hcandidate.copy()
    
    return H
```
And run
```
import pyDOE2
lh = pyDOE2.lhs(2, 100, "correlation")
```
We get out:
```
inf
1.0
1.0
1.0
1.0
```
which is clearly garbage. This is saying that the minimum correlation between points is 1.
But, if we add the transpose as @beckermr suggested we get:
```
0.1131886326160565
0.03932707204394384
0.03932707204394384
0.011408099423550734
```
Which is desirable.

**Comment by beckermr** [comment]
Thanks Tom! This is indeed how I debugged the code in the first place. :)

**Comment by beckermr** [comment]
@RickardSjogren can you please merge this bug fix and cut a release?

**Comment by RickardSjogren** [comment]
Thank you for demonstrating @tmcclintock. I will sure merge and release after the weekend @beckermr

**Pull request merged**
